server:
    port: 8081
spring:
    security:
        oauth2:
            client:
                registration:

                    google:
                        client-id: 103325051261-ocq2crc267j16ijul6le5gcffajaj12d.apps.googleusercontent.com
                        client-secret: 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
                        scope: openid,profile,email

                    naver:
                        client-id: dfOWXpQPsc5cci7Jw7v7
                        client-secret: UdwnX7bXrP
                        authorization-grant-type: authorization_code
                        client-name: naver-client-app
                        redirect-uri: http://localhost:8081/login/oauth2/code/naver
                        scope: profile,email
#                        scope: openid,profile,email

                    kakao:
                        client-id: 1df04390aa5944640f7d2033d23755f9
                        client-secret: Khnx0KchsoHgDIJ8CKnelv5v91iJ8vhr
                        authorization-grant-type: authorization_code
#                        client-authentication-method: POST
                        client-name: client-app
                        redirect-uri: http://localhost:8081/login/oauth2/code/kakao
                        scope: openid,profile_nickname,profile_image
#                        scope: profile_nickname,profile_image

                provider:

                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response

                    kakao:
                        # OpenID Connect 일 경우 jwkSet URI 를 가져와야 하기 때문에 필수항목
                        issuer-uri: https://kauth.kakao.com
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id # OpenID Connect 로 인가서버와 통신하지 않을 경우

    mvc:
      static-path-pattern: /static/**