server:
    port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/oauth2 # 서비스 공급자 위치
#          jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs # OAuth 2.0 JwkSetUri 엔드포인트
#          jws-algorithms: RSA256 # OAuth 2.0 JWS 서명알고리즘
#          audiences: http://localhost:8081 # 수신자위치
#          public-key-location: classpath:certs/publicKey.txt # OAuth 2.0 JWS 검증을 위한 PublicKey 파일위치