server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token/introspect
          client-id: oauth2-client-app
          client-secret: CsJlVOw2en5hjFaIHeJYAbL3KTJGmKRf